gui/visualization/urls.py
from django.urls import path

from gui.visualization import views
from gui.visualization.views import VisualizationOverview, VisualizeSingleSolution, AssignmentSimilarity, \
    EditSingleSolution, TestMetricVisualizationView, VisualizationCompareView

urlpatterns = [
    path('visualization/overview', VisualizationOverview.as_view(), name='visualization-overview'),
    path('visualization/solution/<int:pk>', VisualizeSingleSolution.as_view(), name='visualize-solution'),
    path('visaulization/solution/<int:pk>/edit', EditSingleSolution.as_view(), name='edit-solution'),
    path('visualization/assignment/<int:ass>/solutions', views.fetch_solutions_for_assignment,
         name='visualization-assignment-solutions'),
    path('visualization/assignment/<int:ass>/similarity', AssignmentSimilarity.as_view(),
         name='visualization-assignment-similarity'),
    path('visualization/assignment/<int:ass>/similarity/communicator/<str:com>',
         views.fetch_assignment_similarity_for_communicator, name='visualization-assignment-similarity-communicator'),
    path('visualization/successmetrics', TestMetricVisualizationView.as_view(), name='visualization-test-metrics-overview'),
    path('visualization/compare/<str:sol1>/<str:sol2>', VisualizationCompareView.as_view(), name='visualization-compare'),
    path('visualization/export/similarity', views.export_similarity_report, name='visualization-export-similarity'),
    path('visualization/export/success', views.export_success_report, name='visualization-export-success'),
]

lmaa/urls.py
from django.urls import path, include
from django_select2 import urls as django_select2_urls

urlpatterns = [
    path('', include('gui.home.urls')),
    path('', include('gui.assignments.urls')),
    path('', include('gui.communication.urls')),
    path('', include('gui.testing.urls')),
    path('', include('gui.visualization.urls')),
    path('select2/', include(django_select2_urls)),
]

gui/models.py
import os

import yaml
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from lmaa.settings import BASE_DIR

config_stream = open(os.path.join(BASE_DIR, 'config', 'system_config.yaml'), 'r')
config_map = yaml.safe_load(config_stream)
assignment_maxlength = config_map['management']['database']['maxlength']['assignment']
solution_maxlength = config_map['management']['database']['maxlength']['solution']


class Tag(models.Model):
    name = models.CharField(max_length=64, blank=True)

    class Meta:
        db_table = "tag"


class Classification(models.Model):
    effort = models.IntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
    )
    scope = models.IntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
    )
    tags = models.ManyToManyField(Tag)

    class Meta:
        db_table = "classification"


class Assignment(models.Model):
    semester = models.CharField(max_length=6)
    sheet = models.IntegerField()
    task = models.IntegerField()
    subtask = models.CharField(max_length=8)
    assignment = models.CharField(max_length=assignment_maxlength, blank=True)
    classification = models.OneToOneField(Classification, on_delete=models.CASCADE)

    class Meta:
        db_table = "assignment"


class Testcase(models.Model):
    class Meta:
        db_table = "testcase"


class CompilesTestcase(Testcase):
    active = models.BooleanField(blank=True)

    class Meta:
        db_table = "compiles_testcase"


class ContainsTestcase(Testcase):
    phrase = models.CharField(max_length=64)
    times = models.IntegerField(default=1, blank=True)

    class Meta:
        db_table = "contains_testcase"


class UnitTestcase(Testcase):
    file = models.FileField(upload_to='db_files/', blank=True)

    class Meta:
        db_table = "unit_testcase"


class Solution(models.Model):
    timestamp = models.DateTimeField(blank=True)
    communicator = models.CharField(max_length=64, blank=True)
    solution = models.CharField(max_length=solution_maxlength, blank=True)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    testresults = models.ManyToManyField(Testcase, through='Testresult')

    class Meta:
        db_table = "solution"


class Testresult(models.Model):
    solution = models.ForeignKey(Solution, on_delete=models.CASCADE)
    testcase = models.ForeignKey(Testcase, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(blank=True)
    result = models.BooleanField(blank=True)
    message = models.CharField(
        validators=[
            MaxValueValidator(1024)
        ]
    ),

    class Meta:
        db_table = "testresult"

gui/visualization/models.py
from django.db import models

# Create your models here.

gui/visualization/forms.py
from django import forms
from django.forms import Form


class SolutionEditForm(Form):
    """
    Single field form for viewing and updating a solution
    """
    solution = forms.CharField(widget=forms.Textarea(attrs={'rows': 20}))

gui/visualization/views.py
import os
import statistics
from datetime import datetime

import numpy as np
from django.http import JsonResponse, HttpResponse
from django.urls import reverse
from django.views.generic import TemplateView, FormView
from numpy import ndarray

from gui.assignments.models import Assignment, Solution, Tag
from gui.testing.models import ContainsTestcase, CompilesTestcase, UnitTestcase, CompilesTestresult, ContainsTestresult, \
    UnitTestresult
from gui.visualization.forms import SolutionEditForm
from gui.visualization.tasks import __get_report_folder_path__, generate_similarity_report_for_export, \
    generate_success_report_for_export
from scripts.visualization.metrics import metrics_manager as manager
from scripts.visualization.metrics.success_metric import UnweightedTestResult


class VisualizationOverview(TemplateView):
    """
    Paginated view for displaying assignments and solutions with the option to open the similarity metrics
    """
    template_name = 'visualization/overview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        page = int(self.request.GET.get('page', 1))
        page_size = 10

        assignments = Assignment.objects.order_by('semester', 'sheet', 'task', 'subtask')[
                      page_size * (page - 1):(page_size * page)]

        context['assignments'] = assignments
        context['solutions'] = []
        context['page_obj'] = self.__build_page_obj__(page, page_size)

        return context

    @staticmethod
    def __build_page_obj__(page, page_size):
        """
        build the template variables necessary for pagination
        :param page: page number
        :param page_size: page size
        :return: template object for pagination
        """

        page_obj = {}
        num_assignments = Assignment.objects.order_by('semester', 'sheet', 'task', 'subtask').count()
        max_pages = round(num_assignments / page_size) if (num_assignments % page_size == 0) else round(
            num_assignments / page_size) + 1

        page_obj.__setitem__('has_previous', page != 1)
        page_obj.__setitem__('previous_page_number', page - 1)
        page_obj.__setitem__('number', page)
        page_obj.__setitem__('num_pages', max_pages)
        page_obj.__setitem__('has_next', page != max_pages)
        page_obj.__setitem__('next_page_number', page + 1)

        return page_obj


class VisualizeSingleSolution(TemplateView):
    """
    view for single solution visualization
    """

    template_name = 'visualization/display_solution.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        solution_id = self.kwargs.get('pk')
        solution = Solution.objects.get(id=solution_id)
        context['solution'] = solution

        context['containsTestcases'] = ContainsTestcase.objects.filter(assignment_id=solution.assignment_id) \
            .order_by('phrase').all()
        context['test_results'] = self.__build_existing_test_results__(solution_id)
        context['has_compiles_testcase'] = CompilesTestcase.objects.filter(
            assignment_id=solution.assignment_id).exists()
        context['has_unit_testcase'] = UnitTestcase.objects.filter(assignment_id=solution.assignment_id).exists()

        return context

    def __build_existing_test_results__(self, solution_id: int):
        """
            Build a datastructure containing all testcases/-results of an assignment for use in the template.

            Structure:
            '''
            {
                timestamp_1: {
                    'compiles': Testresult,
                    'contains': {
                        ContainsTestcase1: Testresult,
                        ContainsTestcase2: Testresult,
                    }
                    'unit': Testresult
                },
                ...
            }
            '''
        """

        result = {}

        # get all executed timestamps for the assignment
        timestamps_compiles = CompilesTestresult.objects.filter(solution_id=solution_id) \
            .values_list('timestamp', flat=True) \
            .distinct()
        timestamps_contains = ContainsTestresult.objects.filter(solution_id=solution_id) \
            .values_list('timestamp', flat=True) \
            .distinct()
        timestamps_unit = UnitTestresult.objects.filter(solution_id=solution_id) \
            .values_list('timestamp', flat=True) \
            .distinct()
        timestamps = set(timestamps_compiles.union(timestamps_contains, timestamps_unit).order_by('timestamp'))

        assignment = Solution.objects.get(id=solution_id).assignment

        # for every timestamp...
        for ts in timestamps:
            result[ts] = {}

            # fetch and add compiles testcases/-results
            compiles_test_cases = CompilesTestcase.objects.filter(assignment=assignment)
            compiles_test_results = CompilesTestresult.objects.filter(testcase__assignment_id=assignment.id,
                                                                      solution_id=solution_id,
                                                                      testcase__in=compiles_test_cases,
                                                                      timestamp=ts)
            if compiles_test_results.exists():
                result[ts]['compiles'] = compiles_test_results.first()

            # fetch and add contains testcases/-results
            contains_test_cases = ContainsTestcase.objects.filter(assignment=assignment)
            contains_test_results = ContainsTestresult.objects.filter(testcase__assignment_id=assignment.id,
                                                                      solution_id=solution_id,
                                                                      testcase__in=contains_test_cases,
                                                                      timestamp=ts)
            if contains_test_results.exists():
                result[ts]['contains'] = {}
                for ctr in contains_test_results:
                    ctc = ContainsTestcase.objects.get(id=ctr.testcase_id)
                    if ctc not in result[ts]['contains']:
                        result[ts]['contains'][ctc] = ctr

            # fetch and add unit testcases/-results
            unit_test_cases = UnitTestcase.objects.filter(assignment=assignment)
            unit_test_results = UnitTestresult.objects.filter(testcase__assignment_id=assignment.id,
                                                              solution_id=solution_id,
                                                              testcase__in=unit_test_cases,
                                                              timestamp=ts)
            if unit_test_results.exists():
                result[ts]['unit'] = unit_test_results.first()

        return result


class SolutionWrapper:
    """
    Serializable wrapper for Solutions
    """

    def __init__(self, id, timestamp, communicator) -> None:
        super().__init__()
        self.id = id
        self.timestamp = timestamp
        self.communicator = communicator

    def to_dict(self):
        return {
            'id': self.id,
            'timestamp': self.timestamp,
            'communicator': self.communicator
        }


def __get_wrapped_solutions__(queryset):
    """
    convert a queryset of solutions into serializable SolutionWrappers
    :param queryset: query set to be converted
    :return: converted array of SolutionWrappers
    """

    solutions = []
    for solution in queryset:
        wrapped_solution = SolutionWrapper(solution.id, solution.timestamp, solution.communicator)
        solutions.append(wrapped_solution.to_dict())
    return solutions


def fetch_solutions_for_assignment(request, ass):
    """
    request endpoint for fetching all solutions of an assignment
    :param request: request parameters
    :param ass: assignment to fetch the solutions for
    :return: JsonResponse containing the assignments' solutions
    """

    response = {
        'solutions': __get_wrapped_solutions__(Solution.objects.filter(assignment_id=ass).all())
    }

    return JsonResponse(response)


class AssignmentSimilarity(TemplateView):
    """
    view to display the results of the similarity metrics for a given assignment
    """

    template_name = 'visualization/similarity/assignment_similarity.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        assignment_id = self.kwargs.get('ass')
        context['assignment'] = Assignment.objects.get(id=assignment_id)
        self.__get_similarity_metrics__(context)

        return context

    def __get_similarity_metrics__(self, context):
        communicators = Solution.objects.filter(assignment=context['assignment']) \
            .values_list('communicator', flat=True) \
            .distinct()
        context['communicators'] = communicators

        solutions = Solution.objects.filter(assignment=context['assignment']).all()
        context['solutions'] = solutions

        man = manager.MetricsManager()

        prepared_solutions = self.__prepare_assignment_solutions_single_source__(solutions)
        single_source_cosine_sim_matrix = man.similarity_cosine_single_source(prepared_solutions)
        single_source_cosine_median = man.similarity_cosine_median(solutions.count(), single_source_cosine_sim_matrix)
        single_source_cosine_range = man.similarity_cosine_max(single_source_cosine_sim_matrix) - man.similarity_cosine_min(single_source_cosine_sim_matrix)

        prepared_solutions_with_ids = self.__prepare_assignment_solutions_single_source_with_ids__(solutions)
        single_source_mccabe_complexity = man.mccabe_complexity(prepared_solutions_with_ids)
        single_source_halstead_complexity = man.halstead_metrics(prepared_solutions_with_ids)

templates/visualization/compare_solutions.html
{% extends 'base.html' %}
{% load template_custom_filters_visualization %}
{% load template_custom_filters %}
{% load bootstrap_icons %}

{% block content %}
    <h1>Comparison for {{ first_solution.assignment }} solutions</h1>
    <table class="table table-borderless">
        <tbody>
        <tr>
            <td class="col-6">
                <a class="btn h5" href="{% url 'visualize-solution' pk=first_solution.pk %}">{{ first_solution.timestamp|format_timestamp }}</a>
                <textarea style="font-family: 'Courier New', monospace; font-size: 0.8em" class="w-100" rows="20"
                          disabled="disabled">{{ first_solution.solution }}
                </textarea>
            </td>
            <td class="col-6">
                <a class="btn h5" href="{% url 'visualize-solution' pk=second_solution.pk %}">{{ second_solution.timestamp|format_timestamp }}</a>
                <textarea style="font-family: 'Courier New', monospace; font-size: 0.8em" class="w-100" rows="20"
                          disabled="disabled">{{ second_solution.solution }}
                </textarea>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/visualization/overview.html
{% extends 'base.html' %}
{% load template_custom_filters %}
{% load template_custom_filters_visualization %}
{% load bootstrap_icons %}

{% block content %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div id="search-icon-template" style="display:none;">
        {% bs_icon 'search' extra_classes="bi-valign-text-default" %}
    </div>
    <div id="edit-icon-template" style="display:none;">
        {% bs_icon 'pencil' extra_classes="bi-valign-text-default" %}
    </div>
    <div id="compare-icon-template" style="display:none;">
        {% bs_icon 'file-earmark-diff' extra_classes="bi-valign-text-default" %}
    </div>

    <h1>Assignments overview</h1>

    <style>
        .hover_cursor {
            cursor: pointer;
        }
    </style>

    <div class="row w-100">
        <div class="col-5">
            <table class="table table-striped">
                <thead>
                <tr>
                    <td class="col-8">Assignment</td>
                    <td class="col-3">Solutions</td>
                    <td class="col-auto"></td>
                </tr>
                </thead>
                <tbody>
                {% for assignment in assignments %}
                    <tr class="hover_cursor" id="assignment_select_{{ assignment.id }}">
                        <td>{{ assignment }}</td>
                        <td>{{ assignment.solution_set.all|length }}</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a class="btn btn-primary btn-sm"
                                   href="{% url 'assignments-details' pk=assignment.id %}"
                                   data-toggle="tooltip" data-placement="left"
                                   title="Details">{% bs_icon 'search' extra_classes="bi-valign-text-default" %}</a>
                                {% if assignment.id|has_solutions %}
                                    <a class="btn btn-info btn-sm"
                                       href="{% url 'visualization-assignment-similarity' ass=assignment.id %}"
                                       data-toggle="tooltip" data-placement="right"
                                       title="Solution similarity">{% bs_icon 'circle-half' extra_classes="bi-valign-text-default" %}</a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>

                    <script>
                        $(document).ready(function () {

                            function formatTimestamp(timestamp) {
                                const date = new Date(timestamp);

                                const year = date.getFullYear();
                                const month = String(date.getMonth() + 1).padStart(2, '0'); // Months are zero-based, so we need to add 1
                                const day = String(date.getDate()).padStart(2, '0');
                                const hours = String(date.getHours()).padStart(2, '0');
                                const minutes = String(date.getMinutes()).padStart(2, '0');
                                const seconds = String(date.getSeconds()).padStart(2, '0');

                                return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
                            }

                            $('#assignment_select_{{ assignment.id }}').mousedown(function () {
                                document.getElementById('compare-tab').style.display = "none";
                                $("#compare-table-body").empty()
                                document.getElementById('solutions-tab').style.display = "block";

                                $.ajax({
                                    url: "{% url 'visualization-assignment-solutions' ass=assignment.id %}",
                                    success: function (response) {

                                        $("#solution_table tbody").empty();

                                        response['solutions'].forEach(function (solution) {
                                            var newRow = $("<tr></tr>");

                                            // Add columns to the new row
                                            newRow.append($("<td></td>").text(formatTimestamp(solution.timestamp)));
                                            newRow.append($("<td></td>").text(solution.communicator));

                                            // Add action button with appropriate URL
                                            var iconSvgDetails = $("#search-icon-template").html();
                                            var detailsButton = $("<a></a>")
                                                .addClass("btn btn-primary btn-sm")
                                                .attr("href", "{% url 'visualize-solution' pk=0 %}".replace("0", solution.id))
                                                .html(iconSvgDetails);

                                            var iconSvgEdit = $("#edit-icon-template").html();
                                            var editButton = $("<a></a>")
                                                .addClass("btn btn-secondary btn-sm")
                                                .attr("href", "{% url 'edit-solution' pk=0 %}".replace("0", solution.id))
                                                .html(iconSvgEdit);

                                            var iconSvgCompare = $("#compare-icon-template").html();
                                            var compareButton = $("<a></a>")
                                                .addClass("btn btn-info btn-sm")
                                                .html(iconSvgCompare);
                                            compareButton.mousedown(function () {
                                                document.getElementById('compare-tab').style.display = "block";

                                                let table_body = $("#compare-table-body")

                                                let children = table_body.children();
                                                if (children.length >= 2) {
                                                    return false
                                                }
                                                for (let i = 0; i < children.length; i++) {
                                                    const child = children[i];
                                                    if (child.lastChild.textContent === formatTimestamp(solution.timestamp)) {
                                                        return false;
                                                    }
                                                }

                                                var newCompareRow = $("<tr></tr>")
                                                var newCompareRowHidden = $("<td></td>").text(solution.id)
                                                newCompareRowHidden.hide()
                                                var newCompareRowTimestamp = $("<td></td>").text(formatTimestamp(solution.timestamp))

                                                newCompareRow.append(newCompareRowHidden).append(newCompareRowTimestamp)
                                                table_body.append(newCompareRow)

                                                if (table_body.children().length === 2) {
                                                    $("#compare-btn").show()
                                                    $("#compare-btn-decoy").hide()
                                                }
                                            })

                                            var btnDiv = $("<div></div>").append(detailsButton).append(editButton).append(compareButton);
                                            btnDiv.addClass("btn-group");

                                            var actionColumn = $("<td></td>")
                                            actionColumn.append(btnDiv)

                                            newRow.append(actionColumn);

                                            // Append the new row to the table
                                            $("#solution_table tbody").append(newRow);
                                            $("#solution_table").show()
                                        });
                                    }
                                });
                            });
                        })
                    </script>

                {% endfor %}
                </tbody>
            </table>

            <div class="row d-flex justify-content-center">
                <div class="pagination col-auto">
                    <div class="btn-group btn-group-sm" role="group" aria-label="...">
                        {% if page_obj|lookup:'has_previous' %}
                            <a class="btn btn-secondary btn-sm" href="?page=1">&laquo; first</a>
                            <a class="btn btn-secondary btn-sm"
                               href="?page={{ page_obj|lookup:'previous_page_number' }}">&lsaquo; {{ page_obj|lookup:'previous_page_number' }}</a>
                        {% endif %}

                        <span class="current btn btn-secondary btn-sm" id="current-page"
                              style="background-color: #6c757d !important; border-color: #6c757d !important;color: #fff !important;">
                    {{ page_obj|lookup:'number' }}
                </span>

                        {% if page_obj|lookup:'has_next' %}
                            <a class="btn btn-secondary btn-sm"
                               href="?page={{ page_obj|lookup:'next_page_number' }}">{{ page_obj|lookup:'next_page_number' }}
                                &rsaquo;</a>
                            <a class="btn btn-secondary btn-sm" href="?page={{ page_obj|lookup:'num_pages' }}">last
                                &raquo;</a>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="mt-3 mx-0">
                <a class="btn btn-primary mx-auto" id="export_similarity_report"
                   href="#">{% bs_icon 'list-columns-reverse' extra_classes="bi-valign-default" %} Export report</a>
            </div>
            <script>
                $(document).ready(function () {
                    $('#export_similarity_report').mousedown(function () {
                        window.open('export/similarity')

                        return false;
                    });
                })
            </script>
        </div>
        <div id="solutions-tab" class="col-5" style="display: none">
            <table class="table table-striped" id="solution_table">
                <thead>
                <tr>
                    <td class="col-5">Timestamp</td>
                    <td class="col-5">Communicator</td>
                    <td class="col-auto"></td>
                </tr>
                </thead>
                <tbody>
                {% for solution in solutions %}
                    <tr>
                        <td>{{ solution.timestamp|format_timestamp }}</td>
                        <td>{{ solution.communicator }}</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a class="btn btn-primary btn-sm"
                                   href="{% url 'visualize-solution' pk=solution.id %}">{% bs_icon 'search' extra_classes="bi-valign-text-default" %}</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div id="compare-tab" class="col-2" style="display: none">
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>Compare Solutions</td>
                </tr>
                </thead>
                <tbody id="compare-table-body">

                </tbody>
            </table>
            <a id="compare-btn" class="btn btn-primary">Compare</a>
            <a id="compare-btn-decoy" class="btn btn-primary disabled">Compare</a>
        </div>
        <script>
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
                $("#compare-btn").hide()
                $("#compare-btn-decoy").show()
            })

            $('#compare-btn').mousedown(function () {
                const firstCompareId = document.getElementById("compare-table-body").firstChild.firstChild.textContent
                const secondCompareId = document.getElementById("compare-table-body").lastChild.firstChild.textContent

                console.log(firstCompareId)
                console.log(secondCompareId)

                let url = "{% url 'visualization-compare' sol1=0 sol2=0 %}";
                url = url.replace("0", firstCompareId)
                url = url.split("").reverse().join("").replace("0", secondCompareId.toString().split("").reverse().join("")).split("").reverse().join("");

                window.location.replace(url);
            })
        </script>
    </div>


{% endblock %}